// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lgstvoixptdcqohsxkvo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxnc3R2b2l4cHRkY3FvaHN4a3ZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxMzAzOTUsImV4cCI6MjA2NzcwNjM5NX0.z_rfp9pSx0US8TVnYvQph_gnDZHUj00Ig7o2iGJDUIY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});